name: Linux

on:
  push:

jobs:
  test:
    name: Test and lint
    runs-on: ubuntu-24.04
    env:
      UV_PYTHON: "3.14"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install 3.14

      - name: Install dependencies
        run: >
          uv sync --group dev
          --no-install-package wxpython

      - name: Install wxPython wheel
        run: >
          uv pip install
          https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04/wxpython-4.2.5-cp314-cp314-linux_x86_64.whl

      - name: Run ruff
        run: uv run --no-sync ruff check .

      - name: Run unit tests
        run: uv run --no-sync pytest
